{{- if .Values.gateway.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-ingressgateway
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.global.project }}
  sources:
    - chart: {{ .Values.gateway.source.chart }}
      repoURL: {{ .Values.gateway.source.repoURL }}
      targetRevision: {{ .Values.gateway.source.targetRevision }}
      helm:
        releaseName: {{ .Values.gateway.source.helm.releaseName }}
        ignoreMissingValueFiles: {{ .Values.gateway.source.helm.ignoreMissingValueFiles }}
        valueFiles:
          {{- toYaml .Values.gateway.source.helm.valueFiles | nindent 10 }}
        values: |
          {{- .Values.gateway.source.helm.values | nindent 10 }}
  destination:
    namespace: istio-system
    name: in-cluster
  syncPolicy:
    automated:
      prune: false
    syncOptions:
      - ServerSideApply=true
{{- end }}