# Default values for the Kubeflow Helm chart.
# This file contains configuration options for all components.

# Enable debug mode for verbose logging
# Default: false
debug: false

# Global settings shared across multiple components
global:
  # The ArgoCD project under which applications will be managed
  project: default
  # The namespace ArgoCD is deployed
  namespace: argocd
  # Kubernetes release
  release: argocd

# Configuration for Cert-Manager
certManager:
  # Enable or disable the deployment of Cert-Manager
  enabled: false
  wave: 3
  source:
    # The Helm chart name for Cert-Manager
    chart: cert-manager
    # The repository URL for fetching the chart
    repoURL: https://charts.jetstack.io
    # The specific version of the chart to deploy
    targetRevision: "1.16.3"
    helm:
      # List of additional Helm values files (if any)
      releaseName: cert-manager
      # Inline Helm values configuration
      values:
        crds: 
          enabled: true
          keep: false

istio:
  global: 
    targetRevision: "1.24.2"
    repoURL: 'https://istio-release.storage.googleapis.com/charts'
  components:
    # -- Istio
    base:
      enabled: true
      wave: 3
      namespace: 
        create: true
        labels:
          control-plane: kubeflow
          istio-injection: enabled
      source:
        chart: 'base'
        helm:
          releaseName: "istio-base"
    # -- Istiod
    istiod:
      enabled: true
      wave: 4
      source:
        chart: 'istiod'
        helm:
          releaseName: "istiod"
    # -- Ingress Gateway
    gateway:
      enabled: true
      wave: 4
      source:
        chart: "gateway"
        helm:
          releaseName: "gateway"
          values:
            service:
              type: ClusterIP
            serviceAccount:
              name: istio-ingressgateway-service-account
    # -- Istio Kubeflow Resources
    istioResources:
      enabled: false
      wave: 10
      source:
        path: common/istio-1-17/kubeflow-istio-resources/base
      # destination -> argocd [MAYBE]

kubeflow: 
  global:
    targetRevision: 1.9.1
    repoURL: https://github.com/kubeflow/manifests
  utils:
    # -- Roles
    kubeflowRoles:
      enabled: true
      wave: 10
      source:
        path: common/kubeflow-roles/base
    # -- Profiles
    profiles:
      enabled: true
      wave: 100
      source:
        path: apps/profiles/upstream/overlays/kubeflow
    # -- Admission Webhook
    admissionWebhook:
      enabled: false
      wave: 100
      source:
        path: apps/admission-webhook/upstream/overlays/cert-manager
    # PVC Viewer Controller
    pvcViewerController:
      enabled: true
      wave: 100
      source:
        path: apps/pvcviewer-controller/upstream/default
    # -- Volumes Web App
    volumesWebApp:
      enabled: true
      wave: 100
      source:
        path: apps/volumes-web-app/upstream/overlays/istio
    # -- Example Profile
    exampleProfile:
      enabled: true
      wave: 102
      source:
        path: common/user-namespace/base
    # -- Cluster Local Gateway
    clusterLocalGateway:
      enabled: false
      wave: 200
      source:
        path: common/istio-1-17/cluster-local-gateway/base
        kustomize:
          patches:
          - target:
              kind: Deployment
              name: cluster-local-gateway
              namespace: istio-system
            patch: |-
              - op: replace
                path: /spec/template/spec/containers/0/resources/requests/cpu
                value: 10m

  components: 
    # -- Katib
    katib:
      enabled: false
      wave: 202
      source:
        path: apps/katib/upstream/installs/katib-with-kubeflow
    # -- Models Web App
    modelsWebApp:
      enabled: false
      wave: 201
      source:
        path: contrib/kserve/models-web-app/overlays/kubeflow
    # -- Spark Operator
    sparkOperator:
      enabled: false
      wave: 300
      namespace: 
        create: true # check this [MAYBE]
      source:
        chart: 'spark-operator'
        repoURL: 'https://kubeflow.github.io/spark-operator'
        targetRevision: "1.1.27"
        helm:
          releaseName: "spark-operator"
    # -- Pipelines
    pipelines:
      enabled: false
      wave: 200
      source:
        path: apps/pipeline/upstream/env/cert-manager/platform-agnostic-multi-user
        kustomize:
          patches:
          - target:
              kind: Deployment
              name: ml-pipeline
              namespace: kubeflow
            patch: |-
              - op: replace
                path: /spec/template/spec/containers/0/resources/requests/cpu
                value: 10m
          - target:
              kind: Deployment
              name: ml-pipeline-persistenceagent
              namespace: kubeflow
            patch: |-
              - op: replace
                path: /spec/template/spec/containers/0/resources/requests/cpu
                value: 10m
          - target:
              kind: Deployment
              name: workflow-controller
              namespace: kubeflow
            patch: |-
              - op: replace
                path: /spec/template/spec/containers/0/resources/requests/cpu
                value: 10m
          - target:
              kind: Deployment
              name: mysql
              namespace: kubeflow
            patch: |-
              - op: replace
                path: /spec/template/spec/containers/0/resources/requests/cpu
                value: 10m
          - target:
              kind: StatefulSet
              name: metacontroller
              namespace: kubeflow
            patch: |-
              - op: replace
                path: /spec/template/spec/containers/0/resources/requests/cpu
                value: 10m
    # -- Jupyter Web App
    jupyterWebApp:
      enabled: true
      wave: 100
      source:
        path: apps/jupyter/jupyter-web-app/upstream/overlays/istio
    # -- Notebook Controller
    notebookController:
      enabled: true
      wave: 100
      source:
        path: apps/jupyter/notebook-controller/upstream/overlays/kubeflow
    # -- Dashboard
    centralDashboard:
      enabled: false
      wave: 100
      source:
        path: apps/centraldashboard/upstream/overlays/kserve
        kustomize:
          patches:
          - target:
              kind: ConfigMap
              name: centraldashboard-config
            patch: |-
              - op: replace
                path: /data/links
                value: |
                  {
                    "menuLinks": [
                      {
                        "type": "item",
                        "link": "/jupyter/",
                        "text": "Notebooks",
                        "icon": "book"
                      },
                      {
                        "type": "item",
                        "link": "/volumes/",
                        "text": "Volumes",
                        "icon": "device:storage"
                      }
                    ],
                    "externalLinks": [ ],
                      "quickLinks": [
                        {
                          "text": "Create a new Notebook server",
                          "desc": "Notebook Servers",
                          "link": "/jupyter/new?namespace=kubeflow"
                        }
                      ],
                      "documentationItems": [
                        {
                          "text": "Getting Started with Kubeflow",
                          "desc": "Get your machine-learning workflow up and running on Kubeflow",
                          "link": "https://www.kubeflow.org/docs/started/getting-started/"
                        }
                      ]
                  }

oauth: 
  global:
    targetRevision: 1.9.1
    repoURL: https://github.com/kubeflow/manifests
  components:
    # -- DEX
    dex:
      enabled: true
      wave: 8
      source:
        path: common/dex/overlays/istio
    # -- OIDC
    oidcAuthService:
      enabled: true
      wave: 9
      source:
        path: common/oidc-client/oidc-authservice/base

extras: 
  global:
    targetRevision: 1.9.1
    repoURL: https://github.com/kubeflow/manifests
  components:
    # --Tensorboard Controller
    tensorboardController:
      enabled: false
      wave: 200
      source:
        path: apps/tensorboard/tensorboard-controller/upstream/overlays/kubeflow
    # -- Tensorboard Web App
    tensorboardsWebApp:
      enabled: false
      wave: 200
      source:
        path: apps/tensorboard/tensorboards-web-app/upstream/overlays/istio
    # -- Kuberay
    kuberay:
      enabled: false
      wave: 300
      namespace: 
        create: true # [MAYBE]
      source:
        chart: 'kuberay-operator'
        repoURL: 'https://ray-project.github.io/kuberay-helm/'
        targetRevision: "1.1.0"
        helm:
          releaseName: "kuberay"
    # -- KNative Serving
    knativeServing:
      enabled: false
      wave: 200
      source:
        path: common/knative/knative-serving/overlays/gateways
        kustomize:
          patches:
          - target:
              kind: Deployment
              name: activator
              namespace: knative-serving
            patch: |-
              - op: replace
                path: /spec/template/spec/containers/0/resources/requests/cpu
                value: 15m
          - target:
              kind: Deployment
              name: autoscaler
              namespace: knative-serving
            patch: |-
              - op: replace
                path: /spec/template/spec/containers/0/resources/requests/cpu
                value: 15m
          - target:
              kind: Deployment
              name: domainmapping-webhook
              namespace: knative-serving
            patch: |-
              - op: replace
                path: /spec/template/spec/containers/0/resources/requests/cpu
                value: 15m
          - target:
              kind: Deployment
              name: webhook
              namespace: knative-serving
            patch: |-
              - op: replace
                path: /spec/template/spec/containers/0/resources/requests/cpu
                value: 15m
          - target:
              kind: Deployment
              name: controller
              namespace: knative-serving
            patch: |-
              - op: replace
                path: /spec/template/spec/containers/0/resources/requests/cpu
                value: 15m
    # -- KServe
    kserve:
      enabled: false
      wave: 201
      source:
        path: contrib/kserve/kserve
        kustomize:
          patches:
          - target:
              kind: Deployment
              name: kserve-controller-manager
              namespace: kubeflow
            patch: |-
              - op: replace
                path: /spec/template/spec/containers/0/resources/requests/cpu
                value: 15m