{{- $root := . -}}
{{- range $component, $config := .Values -}}
  {{- if $config.enabled }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $component | lower }}
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "{{ .Values.syncWave }}"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ $config.spec.project }}
  source:
    {{- if $config.spec.sources }}
    sources:
      {{- range $source := $config.spec.sources }}
      - chart: {{ $source.chart | quote }}
        repoURL: {{ $source.repoURL | quote }}
        targetRevision: {{ $source.targetRevision | quote }}
        {{- if $source.helm }}
        helm:
          releaseName: {{ $source.helm.releaseName | quote }}
          ignoreMissingValueFiles: {{ $source.helm.ignoreMissingValueFiles | quote }}
          {{- if $source.helm.valueFiles }}
          valueFiles:
            {{- range $valueFile := $source.helm.valueFiles }}
            - {{ $valueFile | quote }}
            {{- end }}
          {{- end }}
          {{- if $source.helm.values }}
          values: |-
            {{ $source.helm.values | indent 12 }}
          {{- end }}
        {{- end }}
      {{- end }}
    {{- else }}
    source:
      path: {{ $config.spec.source.path | quote }}
      repoURL: {{ $config.spec.source.repoURL | quote }}
      targetRevision: {{ $config.spec.source.targetRevision | quote }}
      {{- if $config.spec.source.kustomize }}
      kustomize:
        patches:
          {{- range $patch := $config.spec.source.kustomize.patches }}
          - target:
              kind: {{ $patch.target.kind | quote }}
              name: {{ $patch.target.name | quote }}
              namespace: {{ $patch.target.namespace | quote }}
            patch: |-
              {{ $patch.patch | indent 12 }}
          {{- end }}
      {{- end }}
    {{- end }}
  destination:
    namespace: {{ $config.spec.destination.namespace | quote }}
    name: {{ $config.spec.destination.name | quote }}
  syncPolicy:
    automated:
      prune: {{ $config.spec.syncPolicy.automated.prune | default false }}
    syncOptions:
      {{- template "syncOptions" $config.spec.syncPolicy }}
  dependencies:
    {{- range $dep := $config.dependsOn }}
    - {{ $dep | lower }}
    {{- end }}
  {{- end }}
  {{- end }}
