{{- define "app.kubeflow.yaml" -}}

{{- $project := .glob.project }}
{{- $argoCDNamespace := .glob.namespace }}
{{- $argoCDReleaseName := .glob.release }}

{{- $targetRevision := .glob.envs.targetRevision }}
{{- $repoURL := .glob.envs.repoURL }}
{{- $namespace := "kubeflow" }}

{{- $wave := include "formatNumber" .config.wave }}

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ printf "%s-%s" $wave (kebabcase .component) }}
  namespace: {{ $argoCDNamespace }}
{{- with .config }}
  annotations:
    {{- if not .wave }}
        {{- fail (printf "Error: Sync wave must be defined.") }}
    {{- else }}
    argocd.argoproj.io/sync-wave: "{{ .wave }}"
    {{- end }}
    app.kubernetes.io/part-of: {{ $argoCDReleaseName }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ $project }}
  syncPolicy:
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
      - Force=true
      {{- if dig "namespace" "create" "" . }}
      - CreateNamespace=true
      {{- end }}
    automated: 
      prune: true
      selfHeal: true
    managedNamespaceMetadata:
      labels:
        {{- dig "namespace" "labels" dict . | toYaml | nindent 8 }}
      annotations:
        {{- dig "namespace" "annotations" dict . | toYaml | nindent 8 }}
  {{- with .source }}
  {{- if .path }}
  source: 
    path: {{ .path }}
    repoURL: {{ dig "repoURL" $repoURL . }}
    targetRevision: {{ dig "targetRevision" $targetRevision . }}
    kustomize: 
      {{- dig "kustomize" dict . | toYaml | nindent 10 }}
  {{- else }}
  sources:
    - chart: {{ .chart }}
      repoURL: {{ dig "repoURL" $repoURL . }}
      targetRevision: {{ dig "targetRevision" $targetRevision . }}
      helm:
        releaseName: {{ .helm.releaseName }}
        ignoreMissingValueFiles: {{ dig "helm" "ignoreMissingValueFiles" "true" . }}
        valueFiles: {{ dig "helm" "valueFiles" list . | toYaml | nindent 10 }}
        valuesObject: {{- dig "helm" "values" dict . | toYaml | nindent 10 }}
        parameters: {{ dig "helm" "parameters" list . | toYaml | nindent 10 }}
  {{- end }}
  {{- end }}
  destination:
    namespace: {{ $namespace }}
    server: https://kubernetes.default.svc
{{- end }}
{{- end }}

{{- $glob := .Values.global -}}
{{- $kubeflowComponents := merge .Values.common .Values.oauth .Values.apps .Values.contrib -}}
{{- $input := dict -}}

{{- range $component, $config := $kubeflowComponents -}}
{{- if $config.enabled }}
    {{- $input = dict "component" $component "config" $config "glob" $glob -}}
    {{- include "app.kubeflow.yaml" $input | fromYaml | toYaml }}
{{- end }}
---
{{ end -}}