# Default values for the Kubeflow Helm chart.
# This file contains configuration options for all components.

# Helm Chart: https://github.com/kubeflow/manifests/tree/v1.9.1

global:
  # The target tag of the Kubeflow manifests
  targetRevision: "v1.9.1"
  # The target repository
  repoURL: "https://github.com/kubeflow/manifests"

# -- Cert Manager 
# Cert Manager is a Kubernetes add-on to automate the management and issuance of TLS certificates from various sources.
certManager:
  certManager:
    enabled: true
    path: common/cert-manager/cert-manager/base
  certManagerIssuer:
    enabled: true
    path: common/cert-manager/kubeflow-issuer/base
    dependsOn:
      - certManager

# -- Istio
istio:
  istioNamespace:
    enabled: true
    path: common/istio-1-22/istio-namespace/base
  istioCrds:
    enabled: true
    path: common/istio-1-22/istio-crds/base
  istio:
    enabled: true
    path: common/istio-1-22/istio-install/overlays/oauth2-proxy
    dependsOn:
      - istioNamespace
      - istioCrds
      - certManager

# -- Authentication
oauth: 
  # -- DEX
  # DEX is an OpenID Connect provider that Kubeflow uses for authentication.
  dex:
    enabled: true
    path: common/dex/overlays/istio
    dependsOn:
      - istio
  oauthProxy:
    enabled: true
    path: common/oauth2-proxy/overlays/m2m-dex-only
    dependsOn:
      - dex

# -- Common
# Common components are used by all Kubeflow components.
common: 
  # -- KNative Serving
  # Knative is used by the KServe official Kubeflow component. It is a Kubernetes-based platform to build, deploy, and manage modern serverless workloads.
  knativeServing:
    enabled: true
    path: common/knative/knative-serving/overlays/gateways
    dependsOn:
      - istio 
  clusterLocalGateway:
    enabled: true
    path: common/istio-1-22/cluster-local-gateway/base
    dependsOn:
      - istio 
  knativeEventing:
    enabled: false
    path: common/knative/knative-eventing/base
    dependsOn:
      - knativeServing
  # -- Network Policies 
  # Network Policies are used to control the traffic flow between different components in the Kubeflow deployment.
  networkPolicies:
    enabled: true
    path: common/networkpolicies/base
    dependsOn:
      - knativeServing
  # -- Roles
  # It contains the default ClusterRoles Kubeflow uses for defining roles for Kubeflow user Profiles. 
  # These roles are currently assigned to users by Profiles (profile-controller and kfam) Service with 
  # the help of Manage Users page in Central Dashboard.
  kubeflowRoles:
    enabled: true
    path: common/kubeflow-roles/base
    dependsOn:
      - networkPolicies
  # -- Istio Kubeflow Resources
  # It contains the Istio resources for Kubeflow components.
  istioResources:
    enabled: true
    path: common/istio-1-22/kubeflow-istio-resources/base
    dependsOn:
      - istio 
      - kubeflowRoles
  # -- User Namespaces  
  # User Namespaces are used to create a namespace for each user in the Kubeflow deployment.
  exampleProfile:
    enabled: false
    path: common/user-namespace/base
    dependsOn:
      - kubeflowRoles

# -- Apps 
# Apps are the main Kubeflow components that provide machine learning capabilities.
apps: 
  # -- Pipelines
  # Kubeflow Pipelines is a platform for building and deploying portable, scalable machine learning (ML) workflows based on Docker containers.
  pipelines:
    enabled: true
    path: apps/pipeline/upstream/env/cert-manager/platform-agnostic-multi-user
    dependsOn:
      - istioResources
  # -- Katib
  # Katib is a scalable and flexible hyperparameter tuning framework for Kubernetes.
  katib:
    enabled: true
    path: apps/katib/upstream/installs/katib-with-kubeflow
    dependsOn:
      - pipelines
  # -- Dashboard
  # The Central Dashboard is a web-based user interface for managing Kubeflow deployments.
  centralDashboard:
    enabled: true
    path: apps/centraldashboard/overlays/oauth2-proxy
    dependsOn:
      - pipelines 
      - katib 
  # -- Admission Webhook
  # The Admission Webhook is a Kubernetes admission controller that validates and mutates resources in the Kubeflow deployment.
  admissionWebhook:
    enabled: true
    path: apps/admission-webhook/upstream/overlays/cert-manager
    dependsOn:
      - centralDashboard
  # -- Notebooks 1.0
  # -- Notebook Controller
  # The Notebook Controller is a Kubernetes controller that manages Jupyter notebooks.
  notebookController:
    enabled: true
    path: apps/jupyter/notebook-controller/upstream/overlays/kubeflow
    dependsOn:
      - admissionWebhook
  # -- Jupyter Web App
  # The Jupyter Web App is a web-based user interface for managing Jupyter notebooks.
  jupyterWebApp:
    enabled: true
    path: apps/jupyter/jupyter-web-app/upstream/overlays/istio
    dependsOn:
      - notebookController
  # PVC Viewer Controller
  # The PVC Viewer Controller is a Kubernetes controller that manages Persistent Volume Claims (PVCs).
  pvcViewerController:
    enabled: true
    path: apps/pvcviewer-controller/upstream/default
    dependsOn:
      - jupyterWebApp
  # -- Profiles & KFAM
  # Profiles is a Kubeflow component that manages user profiles and roles.
  profiles:
    enabled: true
    path: apps/profiles/upstream/overlays/kubeflow
    dependsOn:
      - pvcViewerController
  # -- Volumes Web App
  volumesWebApp:
    enabled: true
    path: apps/volumes-web-app/upstream/overlays/istio
    dependsOn:
      - profiles
  # -- Tensorboard
  # The Tensorboard component is a web-based user interface for visualizing machine learning models.
  # -- Web App
  # The Tensorboards Web App is a web-based user interface for managing TensorBoard instances.
  tensorboardsWebApp:
    enabled: true
    path: apps/tensorboard/tensorboards-web-app/upstream/overlays/istio
    dependsOn:
      - volumesWebApp
  # -- Controller
  # The Tensorboard Controller is a Kubernetes controller that manages TensorBoard instances.
  tensorboardController:
    enabled: true
    path: apps/tensorboard/tensorboard-controller/upstream/overlays/kubeflow
    dependsOn:
      - tensorboardsWebApp
  # -- Training Operator
  # The Training Operator is a Kubernetes operator that manages machine learning training jobs.
  trainingOperator:
    enabled: true
    path: apps/training-operator/upstream/overlays/kubeflow
    dependsOn:
      - volumesWebApp

# -- Contributed Applications
# Contributed applications are additional Kubeflow components that provide machine learning capabilities.
contrib: 
  # -- KServe
  # KServe is a Kubernetes-based serverless inference framework. It is used to deploy and serve machine learning models.
  kserve:
    enabled: true
    path: contrib/kserve/kserve
    dependsOn:
      - pipelines 
  # -- Models Web App
  # The Models Web App is a web-based user interface for managing machine learning models.
  modelsWebApp:
    enabled: true
    path: contrib/kserve/models-web-app/overlays/kubeflow
    dependsOn:
      - kserve

extras: 
  # -- Kuberay
  # Kuberay is a Kubernetes-based platform to build, deploy, and manage modern serverless workloads.
  kuberay:
    enabled: false
    namespace: 
      create: true # check this [MAYBE]
    chart: 'kuberay-operator'
    repoURL: 'https://ray-project.github.io/kuberay-helm/'
    targetRevision: "1.1.0"
    helm:
      releaseName: "kuberay"
  # -- Spark Operator
  # The Spark Operator is a Kubernetes operator that manages Apache Spark applications.
  sparkOperator:
    enabled: false
    namespace: 
      create: true # check this [MAYBE]
    chart: 'spark-operator'
    repoURL: 'https://kubeflow.github.io/spark-operator'
    targetRevision: "1.1.27"
    helm:
      releaseName: "spark-operator"  
