# Helm Chart: https://github.com/mlrun/ce/blob/development/charts/mlrun-ce/values.yaml

userSettings: 
  bucketName: &bucketName ${gcsbucket}
  hostName: &hostName ${hostName}
  registryURL: &registryURL ${registryURL} 
  registrySecretName: &registrySecretName ${registrySecretName}
  whitelistedIPs: &whitelistedIPs ${whitelistedIPs}
  minioPassword: &minioRootPassword ${minioRootPassword}
  minioMLRunBucket: &minioMLRunBucket minio

global:
  externalHostAddress: *hostName
  registry:
    url: *registryURL
    secretName: *registrySecretName

jupyterNotebook:
  persistence:
    size: "30Gi"
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      # ingress.kubernetes.io/rewrite-target: /
      nginx.ingress.kubernetes.io/rewrite-target: /
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      cert-manager.io/issuer: "letsencrypt-production"
      acme.cert-manager.io/http01-edit-in-place: "true" 
      nginx.ingress.kubernetes.io/whitelist-source-range: *whitelistedIPs
    # ingressClassName: nginx
    hosts:
      - host: *hostName
        paths: []
    tls: 
      - enabled: true
        secretName: mlrun-secret-tls

minio:
  # rootUser: minio
  # rootPassword: *minioRootPassword
  # ingress: 
  #   enabled: false
  persistence:
    size: 30Gi

mlrun: 
  ui:
    ingress:
      enabled: false

nuclio:
  controller:
    enabled: true
  dashboard:
    enabled: true
    ingress:
      enabled: false

spark-operator:
  enabled: true

pipelines:
  enabled: true
  # minio:
  #   enabled: true
  #   secretKey: *minioRootPassword
  #   bucket: *minioMLRunBucket

kube-prometheus-stack:
  enabled: true
  alertmanager:
    enabled: false
  grafana:
    ingress:
      enabled: false