{{- define "app.oauth.yaml" -}}

{{- $project := .glob.project }}
{{- $argoCDNamespace := .glob.namespace }}
{{- $argoCDReleaseName := .glob.release }}

{{- $targetRevision := .oauth.targetRevision }}
{{- $repoURL := .oauth.repoURL }}
{{- $namespace := "argocd" }}

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ kebabcase .component }}
  namespace: {{ $argoCDNamespace }}
{{- with .config }}
  annotations:
    {{- if not .wave }}
        {{- fail (printf "Error: Sync wave must be defined.") }}
    {{- else }}
    argocd.argoproj.io/sync-wave: "{{ .wave }}"
    {{- end }}
    app.kubernetes.io/part-of: {{ $argoCDReleaseName }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ $project }}
  syncPolicy:
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
      {{- if dig "namespace" "create" "" . }}
      - CreateNamespace=true
      {{- end }}
    automated: 
      selfHeal: true
    managedNamespaceMetadata:
      labels:
        {{- dig "namespace" "labels" dict . | toYaml | nindent 8 }}
      annotations:
        {{- dig "namespace" "annotations" dict . | toYaml | nindent 8 }}
  sources:
    {{- with .source }}
    - repoURL: {{ $repoURL }}
      targetRevision: {{ $targetRevision }}
      {{- if .path }}
      path: {{ .path }}
      {{- end }}
      {{- if .chart }}
      chart: {{ .chart }}
      helm:
        releaseName: {{ .helm.releaseName }}
        ignoreMissingValueFiles: {{ dig "helm" "ignoreMissingValueFiles" "true" . }}
        valueFiles: {{ dig "helm" "valueFiles" list . | toYaml | nindent 10 }}
        valuesObject: {{- dig "helm" "values" dict . | toYaml | nindent 10 }}
        parameters: {{ dig "helm" "parameters" list . | toYaml | nindent 10 }}
      {{- end }}
    {{- end }}
  destination:
    namespace: {{ $namespace }}
    server: https://kubernetes.default.svc
{{- end }}
{{- end }}

{{- $glob := .Values.global -}}
{{- $oauth := .Values.oauth.global -}}
{{- $input := dict -}}

{{- range $component, $config := .Values.oauth.components -}}
{{- if $config.enabled }}
    {{- $input = dict "component" $component "config" $config "glob" $glob "oauth" $oauth -}}
    {{- include "app.oauth.yaml" $input | fromYaml | toYaml }}
{{- end }}
---
{{ end -}}