{{- define "app.kubeflow.yaml" -}}

{{ $ctx := .ctx }}
# Kustomization for Kubeflow component
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: {{ kebabcase .component }}
{{ with .config }}
  namespace: kubeflow
spec:
  interval: {{ .interval | default "10m" }}
  sourceRef:
    kind: GitRepository
    name: kubeflow
  path: {{ .path }}
  prune: true
  timeout: 3m
  wait: {{ .wait | default true }}
  healthChecks: {{ dig "healthChecks" list . | toYaml | nindent 6 }}
  {{- if ( dig "patch" false . ) }}
  patches:
    {{- range $patchPath := .patch }}
    - {{ include "patch.render" (dict "patchPath" $patchPath "ctx" $ctx ) | nindent 6 }}
    {{- end }}
  {{- end }}
  {{- if ( dig "dependsOn" false . ) }}
  dependsOn:
    {{- range .dependsOn }}
    - name: {{ kebabcase . }}
    {{- end }}
  {{- end }}
{{- end }}
{{- end }}


{{- $kubeflowComponents := merge .Values.common .Values.oauth .Values.apps .Values.contrib .Values.certManager .Values.istio -}}
{{- $ctx := . }}
{{- $input := dict -}}

{{- range $component, $config := $kubeflowComponents -}}
{{- if $config.enabled }}
    {{- $input = dict "component" $component "config" $config "ctx" $ctx -}}
    {{- include "app.kubeflow.yaml" $input | fromYaml | toYaml }}
{{- end }}
---
{{ end -}}