name: Build Kubeflow Helm Chart

on:
  workflow_dispatch:

jobs:
  build-and-push:
    name: Build and Push Helm Chart
    runs-on: [ ubuntu-latest ] 
    permissions:
      contents: read
      id-token: write  # Needed for Workload Identity Federation

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Define chart version
        id: define-chart-version
        run: |
          VERSION=$(yq e '.version' helm/kubeflow/Chart.yaml)
          echo "VERSION=$VERSION" >> "$GITHUB_OUTPUT"

      - uses: google-github-actions/auth@v2
        id: auth
        with:
          token_format: 'access_token'
          project_id: ${{ secrets.PROJECT_ID }}
          service_account: 'github-svc@mlops-development-project.iam.gserviceaccount.com'
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}

      # - name: Verify Authentication
      #   run: |
      #     gcloud auth login --cred-file=${{steps.auth.outputs.credentials_file_path}}

      - name: Package and push helm chart to GCP Artifact Registry
        env:
          VERSION: ${{ steps.define-chart-version.outputs.VERSION }}
          REGION: europe-west8
        run: |
          helm package helm/kubeflow/.
          helm push kubeflow-$VERSION.tgz oci://$REGION-docker.pkg.dev/${{ secrets.PROJECT_ID }}/helm-charts

