name: Build Kubeflow Helm Chart

on:
  workflow_dispatch:

env: 
    REGION: ${{ vars.REGION }}
    SERVICE_ACCOUNT: github-svc@mlops-development-project.iam.gserviceaccount.com
    ACCESS_TOKEN_LIFETIME: 200s
    CHART_PATH: helm/kubeflow

jobs:
  build-and-push:
    name: Build and Push Helm Chart
    runs-on: [ ubuntu-latest ] 
    permissions:
      contents: read
      id-token: write  # Needed for Workload Identity Federation

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Define chart version
        id: define-chart-version
        run: |
          VERSION=$(yq e '.version' $CHART_PATH/Chart.yaml)
          echo "VERSION=$VERSION" >> "$GITHUB_OUTPUT"

      - uses: google-github-actions/auth@v2
        id: auth
        with:
          token_format: 'access_token'
          project_id: ${{ secrets.PROJECT_ID }}
          service_account: ${{ env.SERVICE_ACCOUNT }}
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          access_token_lifetime: ${{ env.ACCESS_TOKEN_LIFETIME }}

      - name: Verify Authentication to Artifact Registry
        run: |
          gcloud auth configure-docker $REGION-docker.pkg.dev --access-token-file=${{steps.auth.outputs.credentials_file_path}}

      - name: Package and push helm chart to GCP Artifact Registry
        env:
          VERSION: ${{ steps.define-chart-version.outputs.VERSION }}
        run: |
          helm package $CHART_PATH/.
          helm push kubeflow-$VERSION.tgz oci://$REGION-docker.pkg.dev/${{ secrets.PROJECT_ID }}/helm-charts

