name: Build Kubeflow Helm Chart

on:
  workflow_dispatch:

jobs:
  build-and-push:
    name: Build and Push Helm Chart
    runs-on: [ ubuntu-latest ] 
    permissions:
      contents: read
      id-token: write  # Needed for Workload Identity Federation

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Define chart version
        id: define-chart-version
        run: |
          VERSION=$(yq e '.version' helm/kubeflow/Chart.yaml)
          echo "VERSION=$VERSION" >> "$GITHUB_OUTPUT"

      - uses: google-github-actions/auth@v2
        id: gcp-login
        with:
          project_id: ${{ secrets.PROJECT_ID }}
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}

      - name: Package and push helm chart to GCP Artifact Registry
        env:
          REGISTRY: ${{ secrets.GCP_ARTIFACT_REGISTRY }}
          VERSION: ${{ steps.define-chart-version.outputs.VERSION }}
        run: |
          helm package helm/kubeflow/.
          helm push kubeflow-$VERSION.tgz oci://$REGISTRY
